# Location of your music files
music_directory		"$XDG_MUSIC_DIR"
music_directory		"~/Music"

# Location of MPD internal playlists
playlist_directory   "~/.mpd/playlists"

# General options
port                 "6600"
restore_paused       "yes"
auto_update          "yes"

# Input plugin for streaming
input {
    plugin "curl"
}

audio_output {
    type            "pipewire"
    name            "PipeWire Sound Server"
    mixer_type      "software"
}

# =============================================================================
# DIRECTORY CREATION COMMANDS
# Run the following commands in your terminal to create the necessary folders:
#
# mkdir -p ~/music
# mkdir -p ~/.mpd/playlist
#
# sudo pacman -S mpd-mpris (mpris addon install)
# systemctl --user enable --now mpd-mpris.service (enable)
# playerctl -l check (check)
#
# https://img.icons8.com/external-vitaliy-gorbachev-flat-vitaly-gorbachev/58/external-vinyl-radio-vitaliy-gorbachev-flat-vitaly-gorbachev.png
# icon
# =============================================================================
