# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# Add extra bindings
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT, R, exec, alacritty -e ssh your-server


#Replace mako with swaync

unbind = SUPER, COMMA
unbind = SUPER ALT, COMMA
unbind = SUPER CTRL, COMMA
unbind = SUPER SHIFT, COMMA
unbind = SUPER SHIFT ALT, COMMA

bind = SUPER, N, exec, swaync-client -t -sw
bind = SUPER, COMMA, exec, swaync-client -d          # Dismiss last notification
bind = SUPER ALT, COMMA, exec, swaync-client -i      # Invoke last notification
bind = SUPER CTRL, COMMA, exec, swaync-client -C     # Toggle silencing notifications
bind = SUPER SHIFT, COMMA, exec, swaync-client -c    # Dismiss all notifications
bind = SUPER SHIFT ALT, COMMA, exec, swaync-client -R  # Restore last notification

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

unbind = SUPER SHIFT, X   #Twitter
unbind = SUPER SHIFT ALT, X #Twitter
unbind = SUPER SHIFT CTRL, G #sabra dios
unbind = SUPER SHIFT, W 
unbind = SUPER SHIFT, G 

unbind = SUPER SHIFT, A #chatgpt
bindd = SUPER SHIFT, A, Gemini, exec, omarchy-launch-webapp "https://gemini.google.com"

unbind = SUPER SHIFT ALT, A #gemini
bindd = SUPER SHIFT ALT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"

unbind = SUPER SHIFT, C #calendar
bindd = SUPER SHIFT ALT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com"

unbind = SUPER SHIFT, E #email
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://gmail.com"

unbind = SUPER SHIFT, S #windows-like
bindd = SUPER SHIFT, S, Screenshot with editing, exec, omarchy-capture-screenshot #windows-scerenshot
bindd = SUPER SHIFT, T, Extract text, exec, omarchy-capture-text-extraction #windows-scerenshot
env = OMARCHY_SCREENSHOT_DIR,/home/lucho/Pictures/Screenshots


bind = alt, $key, exec, hyprswitch gui --mod-key alt_l --key $key --close mod-key-release --reverse-key=mod=$reverse && hyprswitch dispatch
bind = alt $reverse, $key, exec, hyprswitch gui --mod-key alt_l --key $key --close mod-key-release --reverse-key=mod=$reverse && hyprswitch dispatch -r
unbind = SUPER SHIFT ALT, S
bindd = SUPER SHIFT ALT, S, Screenshot to clipboard, exec, omarchy-cmd-screenshot smart clipboard

bindd = CTRL, TAB, Rofi, exec, rofi -show window


bindd = SUPER SHIFT, O, Obsidian, exec, obsidian

bindd = SUPER SHIFT, M, Spotify, exec, spotify

bindd = SUPER SHIFT CONTROL, S, Screenrecording, exec, omarchy-menu screenrecord

bindd = SUPER CONTROL, P, Color picker, exec, pkill hyprpicker || hyprpicker -a

bindd = SUPER SHIFT, C, Calculator, exec, gnome-calculator

# bind brightness

bindd = SUPER SHIFT, L, Brightness up, exec, ~/.config/waybar/scripts/brightness-control.sh up
bindd = SUPER SHIFT, K, Brightness down, exec, ~/.config/waybar/scripts/brightness-control.sh down

# Cambiar seguridad para no cerrar programas
unbind = SUPER, W
bindd = SUPER SHIFT, W, Close window, killactive,
bind = SUPER CTRL SHIFT, W, exec, kill -9 $(hyprctl activewindow -j | jq '.pid')

# Subir y bajar volumen
unbindd = SUPER CTRL, l # Lock system, exec
unbind = SUPER CTRL, l # Lock system, exec
unbindd = SUPER CTRL, k
unbind = SUPER CTRL, k

bind = SUPER CTRL, l, exec, swayosd-client --output-volume raise
bind = SUPER CTRL, k, exec, swayosd-client --output-volume lower

