# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input { 
  kb_options = compose:caps
  kb_layout = latam
  repeat_rate = 40
  repeat_delay = 600
  numlock_by_default = true
  sensitivity = -1
} 

# Scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace

# Enable touchpad gestures for moving focus (helpful on scrolling layout)
# gesture = 3, left,  dispatcher, movefocus, l
# gesture = 3, right, dispatcher, movefocus, r
