bindd = SUPER, a, Toggle scratchpad, togglespecialworkspace, music-scratchpad
bindd = SUPER ALT, a, Move window to scratchpad, movetoworkspacesilent, special:music-scratchpad

windowrule {
    name = music-scratchpad
    match:class = music-scratchpad

    workspace = special:music_scratch
    float = yes
    size = 920 520
    center = yes
    animation = slide top
}


bindd = SUPER, d, Toggle scratchpad, togglespecialworkspace, scratchd
bindd = SUPER ALT, d, Move window to scratchpad, movetoworkspacesilent, special:scratchd

windowrule {
    name = scratchd
    match:class = scratchd

    workspace = special:scratchd
    float = yes
    size = 640 740
    move = 100% -w 0
    animation = slide side

}



