bindd = SUPER, a, Toggle scratchpad A, togglespecialworkspace, scratchpadA
bindd = SUPER ALT, a, Move window to scratchpad A, movetoworkspacesilent, special:scratchpadA


bindd = SUPER, d, Toggle scratchpad D, togglespecialworkspace, scratchpadD
bindd = SUPER ALT, d, Move window to scratchpad D, movetoworkspacesilent, special:scratchpadD

bindd = SUPER, m, Toggle scratchpad M, togglespecialworkspace, scratchpadM
bindd = SUPER ALT, m, Move window to scratchpad M, movetoworkspacesilent, special:scratchpadM
