# windowrule = workspace, match:class qemu
windowrule = float on, match:class com.luchho.weather,size 953 700
windowrule = float on, match:class tui-notepad,size 950 700

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar
