#----------------------Bindings
#unbind = SUPER, SPACE
#bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
  
unbind = SUPER SHIFT, X   #Twitter
unbind = SUPER SHIFT ALT, X #Twitter
unbind = SUPER SHIFT CTRL, G
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, G

unbind = SUPER SHIFT, A
bindd = SUPER SHIFT, A, Gemini, exec, omarchy-launch-webapp "https://gemini.google.com"

unbind = SUPER SHIFT ALT, A
bindd = SUPER SHIFT ALT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"

unbind = SUPER SHIFT, C #calendar
bindd = SUPER SHIFT ALT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com"

unbind = SUPER SHIFT, E #email
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://gmail.com"

unbind = , PRINT, Screenshot with editing, exec, omarchy-cmd-screenshot #disable default 
unbind = SUPER SHIFT, S #windows-like
bindd = SUPER SHIFT, S, Screenshot with editing, exec, omarchy-cmd-screenshot #windows-scerenshot

unbidd = SHIFT, PRINT
unbind = SUPER SHIFT ALT, S, Screenshot to clipboard, exec, omarchy-cmd-screenshot smart clipboard
bindd = SUPER SHIFT ALT, S, Screenshot to clipboard, exec, omarchy-cmd-screenshot smart clipboard

bindd = SUPER SHIFT, O, Obsidian, exec, obsidian

bindd = SUPER SHIFT, M, Spotify, exec, spotify

bindd = SUPER SHIFT CONTROL, S, Screenrecording, exec, omarchy-menu screenrecord

bindd = SUPER CONTROL, P, Color picker, exec, pkill hyprpicker || hyprpicker -a

bindd = SUPER SHIFT, C, Calculator, exec, gnome-calculator

# bind brightness

bindd = SUPER SHIFT, L, Brightness up, exec, ~/.config/waybar/scripts/brightness-control.sh up
bindd = SUPER SHIFT, K, Brightness down, exec, ~/.config/waybar/scripts/brightness-control.sh down

# Cambiar seguridad para no cerrar programas
unbind = SUPER, W
bindd = SUPER SHIFT, W, Close window, killactive,

# Subir y bajar volumen
unbind = SUPER CTRL, L # Lock system, exec
bindeld = SUPER CTRL, l, Volume up, exec, $osdclient --output-volume raise
bindeld = SUPER CTRL, k, Volume down, exec, $osdclient --output-volume lower

# Monitor
# Format: monitor = [port], resolution, position, scale
monitor=,1920x1080@180,auto,auto

#change mouse cursor
exec-once=hyprctl setcursor volantes_cursors 28
exec-once=otd-daemon


# ----------- Input & Device Configuration 
input { 
  kb_options = compose:caps
  kb_layout = latam
  repeat_rate = 40
  repeat_delay = 600
  numlock_by_default = true
  sensitivity = -1
} 
# -----------  Custom Omarchy Look'n'Feel
  
general { 
  gaps_in = 2
  gaps_out = 4
  border_size = 2
} 
decoration {
  rounding = 12
}

# ----------- weather popup waybar
# windowrule = workspace, match:class qemu
windowrule = float on, match:class com.luchho.weather,size 950 700
windowrule = float on, match:class io.github.diegopvlk.Tomatillo,size 400 400
windowrule = float on, match:class tui-notepad,size 950 700

# ----------- Scratchpad
bindd = SUPER, a, Toggle scratchpad A, togglespecialworkspace, scratchpadA
bindd = SUPER ALT, a, Move window to scratchpad A, movetoworkspacesilent, special:scratchpadA

windowrule {
    name = scratchpadA
    match:class = scratchpadA

    workspace = special:scratchpadA
    float = yes
    size = 920 520
    center = yes
    animation = slide top
}


bindd = SUPER, d, Toggle scratchpad D, togglespecialworkspace, scratchpadD
bindd = SUPER ALT, d, Move window to scratchpad D, movetoworkspacesilent, special:scratchpadD

windowrule {
    name = scratchpadD
    match:class = scratchpadD

    workspace = special:scratchpadD
    float = yes
    size = 640 740
    move = 100% -w 0
    animation = slide side

}




